// Dữ liệu mẫu ban đầu cho hệ thống POS Cafe

import type { Product, Employee, Customer, Order } from "~/types";

const COFFEE_IMAGES = [
  "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=200&h=200&fit=crop",
] as const;

function img(index: number): string {
  return COFFEE_IMAGES[index % COFFEE_IMAGES.length]!;
}

export function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
}

export function createSeedProducts(): Product[] {
  const products: Product[] = [
    {
      id: generateId(),
      name: "Cà phê đen",
      price: 25000,
      category: "Cà phê",
      image: img(0),
      description: "Cà phê đen truyền thống",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Cà phê sữa",
      price: 30000,
      category: "Cà phê",
      image: img(1),
      description: "Cà phê sữa đá thơm ngon",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Bạc xỉu",
      price: 32000,
      category: "Cà phê",
      image: img(2),
      description: "Bạc xỉu béo ngậy",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Espresso",
      price: 35000,
      category: "Cà phê",
      image: img(3),
      description: "Espresso đậm đà",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Cappuccino",
      price: 45000,
      category: "Cà phê",
      image: img(4),
      description: "Cappuccino kem béo",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Latte",
      price: 45000,
      category: "Cà phê",
      image: img(0),
      description: "Latte mịn màng",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Americano",
      price: 40000,
      category: "Cà phê",
      image: img(1),
      description: "Americano thanh nhẹ",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Mocha",
      price: 50000,
      category: "Cà phê",
      image: img(2),
      description: "Mocha chocolate",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Trà sen vàng",
      price: 35000,
      category: "Trà",
      image: img(3),
      description: "Trà sen vàng thơm ngát",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Trà đào cam sả",
      price: 40000,
      category: "Trà",
      image: img(4),
      description: "Trà đào cam sả tươi mát",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Trà vải",
      price: 38000,
      category: "Trà",
      image: img(0),
      description: "Trà vải thanh mát",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Trà ổi hồng",
      price: 38000,
      category: "Trà",
      image: img(1),
      description: "Trà ổi hồng tự nhiên",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Trà sữa trân châu",
      price: 42000,
      category: "Trà",
      image: img(2),
      description: "Trà sữa trân châu đường đen",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Matcha latte",
      price: 48000,
      category: "Trà",
      image: img(3),
      description: "Matcha Nhật Bản",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Sinh tố bơ",
      price: 45000,
      category: "Sinh tố",
      image: img(4),
      description: "Sinh tố bơ sánh mịn",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Sinh tố xoài",
      price: 42000,
      category: "Sinh tố",
      image: img(0),
      description: "Sinh tố xoài tươi",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Sinh tố dâu",
      price: 42000,
      category: "Sinh tố",
      image: img(1),
      description: "Sinh tố dâu tây",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Sinh tố việt quất",
      price: 48000,
      category: "Sinh tố",
      image: img(2),
      description: "Sinh tố việt quất",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Sinh tố chuối",
      price: 38000,
      category: "Sinh tố",
      image: img(3),
      description: "Sinh tố chuối bổ dưỡng",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Nước ép cam",
      price: 35000,
      category: "Nước ép",
      image: img(4),
      description: "Nước ép cam tươi",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Nước ép dưa hấu",
      price: 30000,
      category: "Nước ép",
      image: img(0),
      description: "Nước ép dưa hấu mát lạnh",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Nước ép táo",
      price: 35000,
      category: "Nước ép",
      image: img(1),
      description: "Nước ép táo xanh",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Nước ép cà rốt",
      price: 32000,
      category: "Nước ép",
      image: img(2),
      description: "Nước ép cà rốt tươi",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Nước ép ổi",
      price: 30000,
      category: "Nước ép",
      image: img(3),
      description: "Nước ép ổi hồng",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Bánh croissant",
      price: 35000,
      category: "Bánh ngọt",
      image: img(4),
      description: "Bánh croissant bơ Pháp",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Bánh tiramisu",
      price: 45000,
      category: "Bánh ngọt",
      image: img(0),
      description: "Bánh tiramisu cà phê",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Bánh cheesecake",
      price: 48000,
      category: "Bánh ngọt",
      image: img(1),
      description: "Cheesecake New York",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Cookie chocolate",
      price: 25000,
      category: "Bánh ngọt",
      image: img(2),
      description: "Cookie chocolate chip",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Muffin blueberry",
      price: 30000,
      category: "Bánh ngọt",
      image: img(3),
      description: "Muffin việt quất",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Nước suối",
      price: 10000,
      category: "Khác",
      image: img(4),
      description: "Nước suối đóng chai",
      isAvailable: true,
      createdAt: new Date().toISOString(),
    },
  ];
  return products;
}

export function createSeedEmployees(): Employee[] {
  return [
    {
      id: generateId(),
      name: "Nguyễn Văn Admin",
      phone: "0901234567",
      role: "admin",
      schedule: [
        {
          day: "Thứ 2",
          shift: "fullday",
          startTime: "06:00",
          endTime: "22:00",
        },
        {
          day: "Thứ 3",
          shift: "fullday",
          startTime: "06:00",
          endTime: "22:00",
        },
        {
          day: "Thứ 4",
          shift: "fullday",
          startTime: "06:00",
          endTime: "22:00",
        },
        {
          day: "Thứ 5",
          shift: "fullday",
          startTime: "06:00",
          endTime: "22:00",
        },
        {
          day: "Thứ 6",
          shift: "fullday",
          startTime: "06:00",
          endTime: "22:00",
        },
      ],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Trần Thị Nhân Viên",
      phone: "0912345678",
      role: "employee",
      schedule: [
        {
          day: "Thứ 2",
          shift: "morning",
          startTime: "06:00",
          endTime: "14:00",
        },
        {
          day: "Thứ 3",
          shift: "morning",
          startTime: "06:00",
          endTime: "14:00",
        },
        {
          day: "Thứ 4",
          shift: "afternoon",
          startTime: "14:00",
          endTime: "22:00",
        },
        {
          day: "Thứ 5",
          shift: "morning",
          startTime: "06:00",
          endTime: "14:00",
        },
        {
          day: "Thứ 6",
          shift: "afternoon",
          startTime: "14:00",
          endTime: "22:00",
        },
      ],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Lê Văn Barista",
      phone: "0923456789",
      role: "employee",
      schedule: [
        {
          day: "Thứ 2",
          shift: "afternoon",
          startTime: "14:00",
          endTime: "22:00",
        },
        {
          day: "Thứ 3",
          shift: "afternoon",
          startTime: "14:00",
          endTime: "22:00",
        },
        {
          day: "Thứ 4",
          shift: "morning",
          startTime: "06:00",
          endTime: "14:00",
        },
        {
          day: "Thứ 6",
          shift: "morning",
          startTime: "06:00",
          endTime: "14:00",
        },
        {
          day: "Thứ 7",
          shift: "fullday",
          startTime: "06:00",
          endTime: "22:00",
        },
      ],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  ];
}

export function createSeedCustomers(): Customer[] {
  return [
    {
      id: generateId(),
      name: "Phạm Minh Tuấn",
      phone: "0934567890",
      points: 150,
      totalSpent: 1500000,
      visitCount: 25,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Nguyễn Thị Lan",
      phone: "0945678901",
      points: 80,
      totalSpent: 800000,
      visitCount: 12,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Hoàng Văn Đức",
      phone: "0956789012",
      points: 200,
      totalSpent: 2000000,
      visitCount: 35,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Trần Thị Mai",
      phone: "0967890123",
      points: 50,
      totalSpent: 500000,
      visitCount: 8,
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      name: "Vũ Đình Nam",
      phone: "0978901234",
      points: 320,
      totalSpent: 3200000,
      visitCount: 50,
      createdAt: new Date().toISOString(),
    },
  ];
}

export function createSeedOrders(): Order[] {
  return [
    {
      id: generateId(),
      items: [
        {
          productId: "1",
          productName: "Cà phê đen",
          price: 25000,
          quantity: 2,
          note: "",
        },
        {
          productId: "2",
          productName: "Bánh croissant",
          price: 35000,
          quantity: 1,
          note: "",
        },
      ],
      total: 85000,
      discount: 0,
      finalTotal: 85000,
      customerId: null,
      customerPhone: "",
      paymentMethod: "cash",
      employeeId: "1",
      employeeName: "Trần Thị Nhân Viên",
      status: "completed",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: generateId(),
      items: [
        {
          productId: "3",
          productName: "Cappuccino",
          price: 45000,
          quantity: 1,
          note: "Ít đường",
        },
        {
          productId: "4",
          productName: "Bánh tiramisu",
          price: 45000,
          quantity: 1,
          note: "",
        },
      ],
      total: 90000,
      discount: 5000,
      finalTotal: 85000,
      customerId: "1",
      customerPhone: "0934567890",
      paymentMethod: "qr",
      employeeId: "2",
      employeeName: "Lê Văn Barista",
      status: "completed",
      createdAt: new Date(Date.now() - 172800000).toISOString(),
    },
  ];
}
